### PR TITLE
refactor(prisma): export `formatEntitiesKeys`

### PR DESCRIPTION
**Pull request by th3rius**

### CODE REVIEW

**Review by Viserion77 — APPROVED** [review]
LGTM

**Review by marcosalves-bitg — DISMISSED** [review]
LGTM

**Comment by Viserion77** [comment]
are missing `npm i`

**Comment by th3rius** [comment]
> is missing `npm i`

What are you talking about?

**Review by Viserion77 — APPROVED** [review]
LGTM

**Pull request merged**
