### PR TITLE
[FEAT] Custom Forbidden Error

### PR DESCRIPTION
**Pull request by marcofeliponi**
Creates a custom forbidden error.

### CODE REVIEW

**Review by gabrielforster — APPROVED** [review]
LGTM :rocket:

**Review by Viserion77 — DISMISSED** [review]
LGTM

**Review by gabrielforster — APPROVED** [review]
LGTM

**Review by CauaKath — APPROVED** [review]
LGTM

**Review by Viserion77 — APPROVED** [review]

**Pull request merged**
